Repository DILCISBoard/E-ARK-CSIP, pull requests merged in 2020-06, with the labels that each got.

#600 FEAT: Full spec and PDF archive
  archive/index.md
  archive/v2_0/eark-csip-v2-0-1.pdf
  archive/v2_0/eark-csip-v2-0-2.pdf
  archive/v2_0/eark-csip-v2.0.3.pdf
  profile/E-ARK-CSIP-v2-0-0.xml
  profile/E-ARK-CSIP-v2-0-1.xml
  profile/E-ARK-CSIP-v2-0-2.xml
  profile/E-ARK-CSIP-v2-0-3.xml
Labels: enhancement

#596 FIX - Duplicate and obtuse IDs
  profile/E-ARK-CSIP.xml
  specification/implementation/metadata/general-requirements/index.md
Labels: bug

#598 REL: v2.0.4
  profile/E-ARK-CSIP.xml
  specification/implementation/metadata/general-requirements/index.md
Labels: Ready

#604 FIX: Appendix D to list all requirements
  BASE.md
  specification/appendices/appendices.md
  specification/appendices/requirements/index.md
  specification/appendices/requirements/requirements.md
  specification/appendices/requirements/requirements.md.bak
  specification/appendices/requirements/structure.md
  specification/implementation/structure/folders/index.md
  specification/implementation/structure/folders/structure.md
Labels: bug

#606 FIX: Example IDs
  profile/E-ARK-CSIP.xml
  schema/mets.profile.v2-0.xsd
Labels: bug

#608 Fix/images/csip
  specification/figs/fig_3_csip_types.svg
  specification/figs/fig_4_cs_vs_ip.svg
Labels: enhancement

#611 Update of minor text errors (principles)
  specification/specification/principles/index.md
Labels: bug

#614 Update of minor text errors (mets)
  specification/implementation/metadata/mets/index.md
Labels: Typos and text enhancements

#622 FIX: Fig 7 rep names
  specification/figs/fig_7_cs_con_struct.svg
Labels: Typos and text enhancements

#623 FIX: Fig 8 rep names
  specification/figs/fig_8_csip_struct.svg
Labels: Typos and text enhancements

#625 FEAT: Information Package Examples
  .gitignore
  .travis.yml
  examples/IP.AVID.RA.18006.zip
  examples/README.md
  examples/index.md
  examples/minimal_IP_invmets.zip
  examples/minimal_IP_nocrtdt.zip
  examples/minimal_IP_noflscid.zip
  examples/minimal_IP_nomtshdr.zip
  examples/minimal_IP_nopcktyp.zip
  examples/minimal_IP_with_schemas.zip
Labels: enhancement

#626 FIX: Minor site niggles
  Vagrantfile
  archive/index.md
  profile/index.md
  specification/figs/fig_10_csip_full.svg
  specification/figs/fig_11_eark_ip_desc_md.svg
  specification/figs/fig_9_csip_simple.svg
  specification/introduction/index.md
Labels: Typos and text enhancements

#627 REL: Metadata
  profile/E-ARK-CSIP.xml
  specification/metadata.md
  specification/postface/postface-pdf.md
  specification/postface/postface.md
Labels: Ready

#631 FIX: Consistent archive pages.
  archive/index.md
  profile/index.md
Labels: bug
